controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.20
    wheel_radius: 0.032
    publish_rate: 50.0
    use_stamped_vel: false
    cmd_vel_timeout: 0.25
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.6
        has_acceleration_limits: true
        max_acceleration: 1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.5
        has_acceleration_limits: true
        max_acceleration: 4.0
